modLoader="javafml" #mandatory
loaderVersion="[32,)"
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/Mo-Glowstone.json"
issueTrackerURL="https://github.com/MasterGeneral156/MoGlowstone-Mod/issues"
displayURL="https://minecraft.curseforge.com/projects/mo-glowstone"
logoFile="logo-new.png"
credits=""
authors="TheMasterGeneral"
[[mods]] 
modId="moglowstone"
version="2.0.5"
displayName="Mo' Glowstone" #mandatory
description='''
Adding colored glowstone!'''

[[dependencies.moglowstone]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2,]"
    ordering="NONE"
    side="BOTH"