license="${mod_license}"
issueTrackerURL="https://github.com/MasterGeneral156/MoGlowstone-Mod/issues" #optional

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/Mo-Glowstone.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone" #optional
logoFile="logo.png" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ctdcore"
    type="required"
    versionRange="${ctd_core_ver},"
    ordering="NONE"
    side="BOTH"
